server:
  port: 8080

jwt:
  secret: "mySuperSecretKeyForJwtTokenGeneration12345678"
  expiration: 86400000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edopp
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: user
      password: password
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: edopp-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true